name: zqy
channels:
  - pytorch
  - defaults
dependencies:
  - _anaconda_depends=2023.07=py311_0
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiobotocore=2.5.0=py311h06a4308_0
  - aiofiles=22.1.0=py311h06a4308_0
  - aiohttp=3.8.3=py311h5eee18b_0
  - aioitertools=0.7.1=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aiosqlite=0.18.0=py311h06a4308_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda-catalogs=0.2.0=py311h06a4308_0
  - anaconda-client=1.11.3=py311h06a4308_0
  - anaconda-navigator=2.4.2=py311h06a4308_0
  - anaconda-project=0.11.1=py311h06a4308_0
  - anyio=3.5.0=py311h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - arrow=1.2.3=py311h06a4308_1
  - arrow-cpp=11.0.0=py311ha0d4687_0
  - astroid=2.14.2=py311h06a4308_0
  - astropy=5.1=py311hbed6279_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.2=py311h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py311h06a4308_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - babel=2.11.0=py311h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py311h5eee18b_1
  - beautifulsoup4=4.12.2=py311h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=23.3.0=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6a678d5_0
  - bokeh=3.1.1=py311h92b7b1e_0
  - boltons=23.0.0=py311h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - botocore=1.29.76=py311h06a4308_0
  - bottleneck=1.3.5=py311hbed6279_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py311h5eee18b_1002
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - c-blosc2=2.8.0=h6a678d5_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - chardet=4.0.0=py311h06a4308_1003
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311h06a4308_0
  - cloudpickle=2.2.1=py311h06a4308_0
  - clyent=1.2.2=py311h06a4308_1
  - colorama=0.4.6=py311h06a4308_0
  - colorcet=3.0.1=py311h06a4308_0
  - comm=0.1.2=py311h06a4308_0
  - conda=23.7.2=py311h06a4308_0
  - conda-build=3.25.0=py311h06a4308_0
  - conda-content-trust=0.1.3=py311h06a4308_0
  - conda-index=0.2.3=py311h06a4308_0
  - conda-libmamba-solver=23.5.0=py311h06a4308_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=2.1.0=py311h06a4308_0
  - conda-package-streaming=0.8.0=py311h06a4308_0
  - conda-repo-cli=1.0.41=py311h06a4308_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - constantly=15.1.0=py311h06a4308_0
  - contourpy=1.0.5=py311hdb19cb5_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py311h9ce1e76_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.1.1=ha002fc5_10
  - cudnn=8.9.2.26=cuda11_0
  - curl=8.1.1=h5eee18b_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py311h5eee18b_0
  - daal4py=2023.1.1=py311h4cb112f_0
  - dal=2023.1.1=hdb19cb5_48679
  - dask=2023.6.0=py311h06a4308_0
  - dask-core=2023.6.0=py311h06a4308_0
  - datasets=2.12.0=py311h06a4308_0
  - datashader=0.15.0=py311h06a4308_0
  - datashape=0.5.4=py311h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py311h06a4308_0
  - distributed=2023.6.0=py311h06a4308_0
  - docstring-to-markdown=0.11=py311h06a4308_0
  - docutils=0.18.1=py311h06a4308_3
  - entrypoints=0.4=py311h06a4308_0
  - et_xmlfile=1.1.0=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - flake8=6.0.0=py311h06a4308_0
  - flask=2.2.2=py311h06a4308_0
  - fmt=9.1.0=hdb19cb5_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py311h5eee18b_0
  - fsspec=2023.4.0=py311h06a4308_0
  - future=0.18.3=py311h06a4308_0
  - gensim=4.3.0=py311hba01205_1
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - glob2=0.7=pyhd3eb1b0_0
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=2.0.1=py311h6a678d5_0
  - grpc-cpp=1.46.1=h33aed49_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.7.0=py311h021c08c_0
  - hdf5=1.10.6=h3ffc7dd_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.16.2=py311h06a4308_0
  - huggingface_hub=0.15.1=py311h06a4308_0
  - hvplot=0.8.4=py311h06a4308_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - imagecodecs=2021.8.26=py311hb63acbb_2
  - imageio=2.31.1=py311h06a4308_0
  - imagesize=1.4.1=py311h06a4308_0
  - imbalanced-learn=0.10.1=py311h06a4308_1
  - importlib-metadata=6.0.0=py311h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py311h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.8=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.19.2=py311h6410fe4_0
  - ipython=8.12.0=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311h06a4308_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py311h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py311h5eee18b_0
  - jinja2=3.1.2=py311h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.2.0=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jq=1.6=h27cfd23_1000
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311h06a4308_0
  - jupyter=1.0.0=py311h06a4308_8
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.1.0=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.3.0=py311h06a4308_0
  - jupyter_events=0.6.3=py311h06a4308_0
  - jupyter_server=2.5.0=py311h06a4308_0
  - jupyter_server_fileid=0.9.0=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyter_server_ydoc=0.8.0=py311h06a4308_1
  - jupyter_ydoc=0.2.4=py311h06a4308_0
  - jupyterlab=4.0.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - jxrlib=1.1=h7b6447c_2
  - keyring=23.13.1=py311h06a4308_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py311h5eee18b_0
  - lazy_loader=0.2=py311h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.6.2=hab531cd_0
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.1.12=0
  - libcurand=10.3.3.129=0
  - libcurl=8.1.1=h91b91d3_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - liblief=0.12.3=h6a678d5_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm14=14.0.6=hdb19cb5_3
  - libmamba=1.4.1=hdb19cb5_0
  - libmambapy=1.4.1=py311hdb19cb5_0
  - libnghttp2=1.52.0=ha637b67_1
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.22=he621ea3_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h0d84882_2
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzopfli=1.0.3=he6710b0_0
  - linkify-it-py=2.0.0=py311h06a4308_0
  - llvmlite=0.40.0=py311he621ea3_0
  - locket=1.0.0=py311h06a4308_0
  - lxml=4.9.1=py311h1edc446_0
  - lz4=4.3.2=py311h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h7b6447c_2
  - markdown=3.4.1=py311h06a4308_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib=3.7.1=py311h06a4308_1
  - matplotlib-base=3.7.1=py311ha02d727_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdit-py-plugins=0.3.0=py311h06a4308_0
  - mdurl=0.1.0=py311h06a4308_0
  - mistune=0.8.4=py311h5eee18b_1000
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=mpich
  - mpich=4.1.1=hbae89fd_0
  - mpmath=1.2.1=py311h06a4308_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - multidict=6.0.2=py311h5eee18b_0
  - multipledispatch=0.6.0=py311h06a4308_0
  - multiprocess=0.70.14=py311h06a4308_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py311h06a4308_1
  - navigator-updater=0.4.0=py311h06a4308_0
  - nbclassic=0.5.5=py311h06a4308_0
  - nbclient=0.5.13=py311h06a4308_0
  - nbconvert=6.5.4=py311h06a4308_0
  - nbformat=5.7.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py311h06a4308_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nltk=3.7=pyhd3eb1b0_0
  - notebook=7.0.1=pyhd8ed1ab_0
  - notebook-shim=0.2.2=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.57.0=py311ha02d727_0
  - numexpr=2.8.4=py311h65dcdc2_1
  - numpy=1.24.3=py311h08b1b3b_1
  - numpy-base=1.24.3=py311hf175353_1
  - numpydoc=1.5.0=py311h06a4308_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.10=py311h5eee18b_0
  - openssl=1.1.1u=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.0=py311h06a4308_0
  - pandas=1.5.3=py311hba01205_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=1.1.0=py311h06a4308_0
  - param=1.13.0=py311h06a4308_0
  - parsel=1.6.0=py311h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.17.2=h6a678d5_0
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pathspec=0.10.3=py311h06a4308_0
  - patsy=0.5.3=py311h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - pep8=1.7.1=py311h06a4308_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311h6a678d5_0
  - pip=23.1.2=py311h06a4308_0
  - pkginfo=1.9.6=py311h06a4308_0
  - platformdirs=2.5.2=py311h06a4308_0
  - plotly=5.9.0=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - ply=3.11=py311h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=8.0.0=pyhd3eb1b0_1
  - py-lief=0.12.3=py311h6a678d5_0
  - pyarrow=11.0.0=py311hd8e8d9b_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycodestyle=2.10.0=py311h06a4308_0
  - pycosat=0.6.4=py311h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py311h06a4308_0
  - pycurl=7.45.2=py311h37d81fd_0
  - pydispatcher=2.0.5=py311h06a4308_2
  - pydocstyle=6.3.0=py311h06a4308_0
  - pyerfa=2.0.0=py311h5eee18b_0
  - pyflakes=3.0.1=py311h06a4308_0
  - pygments=2.15.1=py311h06a4308_1
  - pyjwt=2.4.0=py311h06a4308_0
  - pylint=2.16.2=py311h06a4308_0
  - pylint-venv=2.3.0=py311h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyodbc=4.0.34=py311h6a678d5_0
  - pyopenssl=23.0.0=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyqt=5.15.7=py311h6a678d5_0
  - pyqt5-sip=12.11.0=py311h6a678d5_0
  - pyqtwebengine=5.15.7=py311h6a678d5_0
  - pyrsistent=0.18.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - pytables=3.8.0=py311h43249b6_2
  - pytest=7.3.1=py311h06a4308_0
  - python=3.11.3=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lmdb=1.4.1=py311h6a678d5_0
  - python-lsp-black=1.2.1=py311h06a4308_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py311h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.1=py311h6a678d5_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python_abi=3.11=2_cp311
  - pytoolconfig=1.2.5=py311h06a4308_1
  - pytorch=2.0.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py311h06a4308_0
  - pyviz_comms=2.3.0=py311h06a4308_0
  - pywavelets=1.4.1=py311h5eee18b_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py311h5eee18b_1
  - pyzmq=25.1.0=py311h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py311h06a4308_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.2.2=py311h06a4308_0
  - qtconsole=5.4.2=py311h06a4308_0
  - qtpy=2.2.0=py311h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - queuelib=1.5.0=py311h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py311h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.29.0=py311h06a4308_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - requests-toolbelt=0.9.1=pyhd3eb1b0_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rope=1.7.0=py311h06a4308_0
  - rtree=1.0.1=py311h06a4308_0
  - ruamel.yaml=0.17.21=py311h5eee18b_0
  - ruamel_yaml=0.17.21=py311h5eee18b_0
  - s3fs=2023.4.0=py311h06a4308_0
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scikit-image=0.20.0=py311h6a678d5_0
  - scikit-learn=1.2.2=py311h6a678d5_1
  - scikit-learn-intelex=2023.1.1=py311h06a4308_0
  - scipy=1.10.1=py311h08b1b3b_1
  - scrapy=2.8.0=py311h06a4308_0
  - seaborn=0.12.2=py311h06a4308_0
  - secretstorage=3.3.1=py311h06a4308_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=67.8.0=py311h06a4308_0
  - sip=6.6.2=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py311h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py311h06a4308_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.4=py311h06a4308_0
  - sphinx=5.0.2=py311h06a4308_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.3=py311h06a4308_1
  - spyder-kernels=2.4.3=py311h06a4308_0
  - sqlalchemy=1.4.39=py311h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py311h5eee18b_1
  - sympy=1.11.1=py311h06a4308_0
  - tabulate=0.8.10=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tbb4py=2021.8.0=py311hdb19cb5_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=py311h06a4308_0
  - terminado=0.17.1=py311h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - tokenizers=0.13.2=py311he7d60b5_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py311h06a4308_0
  - tomlkit=0.11.1=py311h06a4308_0
  - toolz=0.12.0=py311h06a4308_0
  - torchaudio=2.0.2=py311_cu118
  - torchtriton=2.0.0=py311
  - tornado=6.2=py311h5eee18b_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - traitlets=5.7.1=py311h06a4308_0
  - transformers=4.29.2=py311h06a4308_0
  - twisted=22.10.0=py311h5eee18b_0
  - typing-extensions=4.6.3=py311h06a4308_0
  - typing_extensions=4.6.3=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - uc-micro-py=1.0.1=py311h06a4308_0
  - ujson=5.4.0=py311h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.11=h5eee18b_0
  - urllib3=1.26.16=py311h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=0.58.0=py311h06a4308_4
  - werkzeug=2.2.3=py311h06a4308_0
  - whatthepatch=1.0.2=py311h06a4308_0
  - wheel=0.38.4=py311h06a4308_0
  - widgetsnbextension=4.0.5=py311h06a4308_0
  - wrapt=1.14.1=py311h5eee18b_0
  - wurlitzer=3.0.2=py311h06a4308_0
  - xarray=2022.11.0=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xyzservices=2022.9.0=py311h06a4308_1
  - xz=5.4.2=h5eee18b_0
  - y-py=0.5.9=py311h52d8a92_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.7.0=h295c915_1
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.8.1=py311h5eee18b_0
  - ypy-websocket=0.8.2=py311h06a4308_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zict=2.2.0=py311h06a4308_0
  - zipp=3.11.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zlib-ng=2.0.7=h5eee18b_0
  - zope=1.0=py311h06a4308_1
  - zope.interface=5.4.0=py311h5eee18b_0
  - zstandard=0.19.0=py311h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.1
      - docker-pycreds==0.4.0
      - dominate==2.8.0
      - einops==0.6.1
      - fedlab==1.3.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.2
      - lpips==0.1.4
      - munch==4.0.0
      - oauthlib==3.2.2
      - opencv-python==4.8.0.74
      - pathtools==0.1.2
      - protobuf==4.23.4
      - pynvml==11.5.0
      - pytorch-fid==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sentry-sdk==1.29.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorboardx==2.6.2.2
      - torchsde==0.2.5
      - torchvision==0.15.2
      - trampoline==0.1.2
      - wandb==0.15.7
      - yacs==0.1.8
prefix: /home/zqy2139219/anaconda3
